# Generated by Django 4.0.2 on 2022-09-15 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_module', '0003_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['slug']},
        ),
    ]
